sudo: required

services:
  - docker

language:
  - python
python:
  - "3.6"
install:
  - pip install docker

script:
  #- travis_wait 3600 python main.py sync -f "$IMAGES_FILENAME" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" -t="$SYNC_TYPE"
  - curl http://metadata.google.internal/computeMetadata/v1/instance/zone -H "Metadata-Flavor:Google"
  - git add -A
  - git commit -m 'add google script'
  - git push origin master

notifications:
  email: false