sudo: required

services:
  - docker

language:
  - python
python:
  - "3.6"
install:
  - pip install docker

script:
  - travis_wait 3600 python main.py sync -f "$IMAGES_FILENAME" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

notifications:
  email: false